apiVersion: v2
name: multicluster
description: Redpanda multicluster operator helm chart
type: application

# The operator helm chart is considered part of the operator itself. Therefore
# version == appVersion. Our charts' versions, don't include a leading `v`, so
# we match that precedence here.
version: 25.2.1-beta1
appVersion: v25.2.1-beta1
kubeVersion: ">= 1.25.0-0"

sources:
  - https://github.com/redpanda-data/redpanda-operator/tree/main/charts/multicluster
icon: https://go.redpanda.com/hubfs/Redpandas/operator-panda.png
maintainers:
  - name: redpanda-data
    url: https://github.com/orgs/redpanda-data/people

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://docs.redpanda.com
    - name: "Helm (>= 3.6.0)"
      url: https://helm.sh/docs/intro/install/
  artifacthub.io/images: |
    - name: redpanda-multicluster-operator
      image: docker.redpanda.com/redpandadata/redpanda-operator:v25.2.1-beta1
    - name: redpanda
      image: docker.redpanda.com/redpandadata/redpanda:v25.2.1
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Seamless Upgrades