---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.3
  name: stretchclusters.cluster.redpanda.com
spec:
  group: cluster.redpanda.com
  names:
    kind: StretchCluster
    listKind: StretchClusterList
    plural: stretchclusters
    shortNames:
    - sc
    singular: stretchcluster
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].message
      name: Status
      type: string
    - jsonPath: .status.conditions[?(@.type=="LicenseValid")].message
      name: License
      type: string
    name: v1alpha2
    schema:
      openAPIV3Schema:
        description: StretchCluster defines the CRD for StretchCluster configuration.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            type: object
          status:
            default:
              conditions:
              - lastTransitionTime: "1970-01-01T00:00:00Z"
                message: Waiting for controller
                reason: NotReconciled
                status: Unknown
                type: Ready
              - lastTransitionTime: "1970-01-01T00:00:00Z"
                message: Waiting for controller
                reason: NotReconciled
                status: Unknown
                type: Healthy
              - lastTransitionTime: "1970-01-01T00:00:00Z"
                message: Waiting for controller
                reason: NotReconciled
                status: Unknown
                type: LicenseValid
              - lastTransitionTime: "1970-01-01T00:00:00Z"
                message: Waiting for controller
                reason: NotReconciled
                status: Unknown
                type: ResourcesSynced
              - lastTransitionTime: "1970-01-01T00:00:00Z"
                message: Waiting for controller
                reason: NotReconciled
                status: Unknown
                type: ConfigurationApplied
              - lastTransitionTime: "1970-01-01T00:00:00Z"
                message: Waiting for controller
                reason: NotReconciled
                status: Unknown
                type: Quiesced
              - lastTransitionTime: "1970-01-01T00:00:00Z"
                message: Waiting for controller
                reason: NotReconciled
                status: Unknown
                type: Stable
            properties:
              conditions:
                description: Conditions holds the conditions for the StretchCluster.
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              configVersion:
                description: |-
                  ConfigVersion contains the configuration version written in
                  Redpanda used for restarting broker nodes as necessary.
                type: string
              license:
                description: |-
                  LicenseStatus contains information about the current state of any
                  installed license in the Redpanda cluster.
                properties:
                  expiration:
                    format: date-time
                    type: string
                  expired:
                    type: boolean
                  inUseFeatures:
                    items:
                      type: string
                    type: array
                  organization:
                    type: string
                  type:
                    type: string
                  violation:
                    type: boolean
                required:
                - inUseFeatures
                - violation
                type: object
              nodePools:
                description: |-
                  NodePools contains information about the node pools associated
                  with this stretch cluster.
                items:
                  description: EmbeddedNodePoolStatus defines the observed state of
                    any node pools tied to this cluster
                  properties:
                    condemnedReplicas:
                      description: |-
                        CondemnedReplicas is the number of replicas that will be decommissioned
                        as part of a scaling down operation.
                      format: int32
                      type: integer
                    desiredReplicas:
                      description: |-
                        DesiredReplicas is the number of replicas that ought to be
                        run for the cluster. It combines the desired replicas across
                        all node pools.
                      format: int32
                      type: integer
                    name:
                      description: Name is the name of the pool
                      type: string
                    outOfDateReplicas:
                      description: |-
                        OutOfDateReplicas is the number of replicas that don't currently
                        match their node pool definitions. If OutOfDateReplicas is not 0
                        it should mean that the operator will soon roll this many pods.
                      format: int32
                      type: integer
                    readyReplicas:
                      description: |-
                        ReadyReplicas is the number of replicas whose readiness probes are
                        currently passing.
                      format: int32
                      type: integer
                    replicas:
                      description: |-
                        Replicas is the number of actual replicas currently across
                        the node pool. This differs from DesiredReplicas during
                        a scaling operation, but should be the same once the cluster
                        has quiesced.
                      format: int32
                      type: integer
                    runningReplicas:
                      description: |-
                        RunningReplicas is the number of replicas that are actively in a running
                        state.
                      format: int32
                      type: integer
                    upToDateReplicas:
                      description: |-
                        UpToDateReplicas is the number of replicas that currently match
                        their node pool definitions.
                      format: int32
                      type: integer
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
